---
title: "Day 5: All About Heuristics"
author: 
  - name: Devjyoti Chakrabarti
    affiliation: University of Oxford 
format: 
     revealjs:
      theme: default
      incremental: true 
---

<div>

### Recap

-   People don't have unlimited cognitive abilities and limited attention to make decisions (bounded rationality)

-   To make the decision making process simpler, people rely on heuristics/mental shortcuts

-   Although convenient, these shortcuts can be the source of many major errors and biases

</div>

------------------------------------------------------------------------

<div>

### Today's Agenda

-   Delve deeper into these heuristics

-   Understand two important behavioural economics theories:

    1.  Nudge Theory

    2.  Prospect Theory

</div>

------------------------------------------------------------------------

<div>

### A Slight Detour

-   Answer the questions given to you with the first answer that comes to your mind. You have 1 minute to answer all the questions.

</div>

------------------------------------------------------------------------

<div>

### Nudge Theory

-   Highly recommended reading: Thinking, Fast and Slow by Daniel Kahneman

-   We want to start thinking about how to solve these puzzles of human thought and make sense of these seeming contradictions

-   The workings of the brain consists of two components or systems

    -   System 1 is the fast and intuitive

    -   System 2 is the slow and reflective

</div>

------------------------------------------------------------------------

<div>

### Automatic System (System 1)

-   "Action without thought". This system is responsible for rapid and instinctive decisions

-   Examples: reaction when a ball is thrown at you unexpectedly

-   Fun fact: This system is associated with the oldest parts of the brain which we share with lizards and puppies[^1]

</div>

[^1]: Philip Lieberman, Human Language and Our Reptilian Brain (Cambridge, MA: Harvard University Press, 2002); Joseph LeDoux, “The Emotional Brain, Fear, and the Amygdala,” Cellular and Molecular Neurobiology 23, no. 4–5 (2003): 727–38.\

------------------------------------------------------------------------

<div>

### Reflective System (System 2)

-   This is the more deliberate and self-conscious system.

-   Example: whats 239 \* 196

-   The Automatic System can be thought of as your gut feeling while the reflective system is your conscious thought.

</div>

------------------------------------------------------------------------

<div>

+-----------------------------+------------------------------+
| Automatic System (System 1) | Reflective System (System 2) |
+=============================+:============================:+
| Uncontrolled                | Controlled                   |
|                             |                              |
| Effortless                  | Effortful                    |
|                             |                              |
| Associative                 | Deductive                    |
|                             |                              |
| Fast                        | Slow                         |
|                             |                              |
| Unconscious                 | Self-aware                   |
|                             |                              |
| Skilled                     | Rule-following               |
+-----------------------------+------------------------------+

</div>

------------------------------------------------------------------------

<div>

### More examples of both systems

1.  When told the temperature in Celsius, most people have an Automatic System reaction while interpreting temperature in Fahrenheit requires use of the Reflective System

2.  People speak their native languages using their Automatic Systems and tend to struggle to speak another language using their Reflective Systems.

</div>

------------------------------------------------------------------------

<div>

### Back to the Detour (Cognitive Reflection Test)[^2]

1.  A bat and ball cost \$1.10 in total. The bat costs \$1.00 more than the ball. How much does the ball cost?

2.  If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?

3.  Mary’s mother had four children. The youngest three are named: Spring, Summer, and Autumn. What is the eldest child’s name?\

</div>

[^2]: Thaler, R. H., & Sunstein, C. R. (2021). Nudge: The Final Edition. Penguin Publishing.

------------------------------------------------------------------------

<div>

-   The most common answers to these questions is 10 cents, 100 minutes and Winter. While the correct answers are 5 cents, 5 minutes and Mary respectively.

-   Students from a lot of top universities were asked some of these questions (MIT, Harvard, Princeton) and the wrong answers tended to be popular.[^3]

</div>

[^3]: Shane Frederick, “Cognitive Reflection and Decision Making,” Journal of Economic Perspectives 19, no. 4 (2005): 25–42.\

------------------------------------------------------------------------

::: {style="font-size: 0.875em"}
### What is the Nudge in Nudge Theory

-   So far we have seen that because people can't think deeply about each choice they face so they tend to accept questions as they are framed instead of trying to consider answers under alternative formulations.

-   What this suggests to us is that people are "nudge-able". Their choices, even in life’s most important decisions, are influenced in ways that would not be anticipated in a standard economic framework.

-   Nudge: "a way to manipulate people’s choices to lead them to make specific decisions... An essential aspect of nudges is that they are not coercive"[^4]
:::

[^4]: <https://news.uchicago.edu/explainer/what-is-behavioral-economics>

------------------------------------------------------------------------

::: {.nonincremental style="font-size: 0.775em"}
### Examples of Nudges {.nonincremental}

-   Nudges through provision of information

    -   Calorie counts on menus

    -   Packaging of food products

-   Changes to environment

    -   Having fewer lifts in buildings

    -   Changing default options on phones

-   Financial (dis)incentives to take particular courses of actions

    -   Higher taxes on cigarettes and subsidies for electric vehicles

    -   Positive gamification and mobile apps: Qapital, fitness apps[^5]
:::

[^5]: Cotton V, Patel MS. Gamification Use and Design in Popular Health and Fitness Mobile Applications. Am J Health Promot. 2019 Mar;33(3):448-451. doi: 10.1177/0890117118790394. Epub 2018 Jul 26. PMID: 30049225; PMCID: PMC6348030.

------------------------------------------------------------------------

::: {style="font-size: 0.775em"}
### Social Nudges

-   Social influence is one of the most effective ways to nudge

-   Social influence comes through two categories:

    -   Information

    -   Peer pressure

-   Some examples of the power of social nudges are:

    -   The academic effort of college students is influenced by their peers

    -   Charity donations/Confirm shaming

    -   American judicial system
:::

------------------------------------------------------------------------

<div>

### Conclusion

-   People can be nudged to make certain choices and decisions

-   Nudges are inherently non-coercive

-   Nudges make us act reflexively instead of reflectively

-   People's desire to conform make social nudges very powerful

</div>

------------------------------------------------------------------------

<div>

### Prospect Theory[^6]

-   Emerging out of a series of empirical results, it is a critique of the expected utility theory for analyzing choices under uncertainty.

-   Prospect theory focuses on gains and losses (in place of expected values) and decision weights (replacing probabilities)

</div>

[^6]: Kahneman, D., & Tversky, A. (1979). Prospect Theory: An Analysis of Decision under Risk. *Econometrica*, *47*(2), 263–291. https://doi.org/10.2307/1914185

------------------------------------------------------------------------

<div>

### Certainty Effects

-   In expected utility theory, the utilities of outcomes are weighted by their probabilities.

-   Problem 1: Choose between

    +----------------------+---------------------+
    | A                    | **B**               |
    +:====================:+:===================:+
    | 2500 with prob. 0.33 | 2400 with certainty |
    |                      |                     |
    | 2400 with prob 0.66  |                     |
    |                      |                     |
    | 0 with prob. 0.01    |                     |
    +----------------------+---------------------+

</div>

------------------------------------------------------------------------

::: {style="font-size: 0.775em"}
-   Problem 2: Choose between

    +----------------------+----------------------+
    | C                    | D                    |
    +:====================:+:====================:+
    | 2500 with prob. 0.33 | 2400 with prob. 0.34 |
    |                      |                      |
    | 0 with prob. 0.67    | 0 with prob. 0.66    |
    +----------------------+----------------------+

-   For Problem 1, 82% choose option B and 18% choose option A ($N=72$). For Problem 2, 83% choose option C and the remaining option D ($N=72$).

-   But for $u(0) = 0$

    $$
    \begin{align*}
       u(2400) &> 0.33 u(2500) + 0.66 u(2400) \text{ and} \\
       0.34 u(2400) &> 0.33 u(2500)
    \end{align*}
    $$

-   Certainty effect: people overweight outcomes that are considered certain, relative to outcomes which are merely probable. Certainty increases the aversiveness of losses as well as the desirability of gains.
:::

------------------------------------------------------------------------

::: {style="font-size: 0.875em"}
### Isolation Effect

-   In order to simplify the choice between alternatives, people often disregard components that the alternatives share, and focus on the components that distinguish them

-   Consider the following two-stage game. In the first stage, there is a probability of .75 to end the game without winning anything, and a probability of .25 to move into the second stage. If you reach the second stage you have a choice between a 80 percent chance of getting 4000 or 3000 with certainty.

-   Of 141 subjects who answered Problem 10, 78 per cent chose the latter prospect
:::

------------------------------------------------------------------------

<div>

### Loss Aversion

-   It refers to an individual's tendency to prefer avoiding losses to acquiring equivalent gains. The loss felt from money, or any other valuable object, can feel worse than gaining that same thing. "It’s better not to lose \$20, than to find \$20."

-   It grows as the stakes of a choice go higher. Example: financial market decisions

-   This is easy to exploit. Example: free trial periods

</div>

------------------------------------------------------------------------

::: {style="font-size: 0.775em"}
### Example: Brazil and Mosquito Gene Editing[^7]

-   To prevent the spread of mosquito-borne viruses, such as Zika, yellow fever, and dengue, Brazil tried a solution involving genetic engineering.

-   The same species of mosquitoes was modified to be all-male, not bite, and carry a self-destructive gene designed to kill them and all their progeny. This novel method was an extremely risky operation for Brazil to undertake that would have cost the country if it failed, but save millions of lives if it worked.

-   More risk averse nations in Europe continue to lag in comparison to innovative nations like Brazil. Even though these countries would greatly benefit from trying new and emerging technologies to address challenges with crop pests, their loss aversion encourages them to stick to the “safe” option instead
:::

[^7]: https://www.labiotech.eu/medical/oxitec-dengue-zika-brazil/

------------------------------------------------------------------------

<div>

### Reference Dependence

-   We think about our decisions not in terms of absolutes but relative to some status quo/baseline

-   People’s perception of value is influenced by the way options are framed, and their satisfaction or dissatisfaction is determined by comparing outcomes to their expectations or previous experiences.

-   Example: would you rather work in a company where everyone earns \$100,000 or where you earn \$110,000 and everyone else earns \$120,000.

</div>

------------------------------------------------------------------------

<div>

### Back to Framing Effects Study

-   Program A: 200 people will be saved \[72%\]

    Program B: $1/3$ probability 600 will be saved, $2/3$ probability that no people will be saved

-   Program C: 400 people will die

    Program D: $1/3$ probability nobody will die, $2/3$ probability that 600 people will die \[78%\]

</div>

------------------------------------------------------------------------

<div>

### Conclusion

-   Prospect theory is a critique of expected utility theory

-   Certainty effect, reflection effect, isolation effect

-   Framing effects as a recurring example illustrates loss aversion and reference dependence.

</div>
