---
title: "Behavioural Economics Cambridge Tradition 2024"
author: 
  - name: Devjyoti Chakrabarti
    email: devjyoti.chakrabarti@economics.ox.ac.uk 
    affiliations:
      - name: University of Oxford
theme: lux      
---

> "We think, each of us, that we're much more rational than we are."
>
> -- Daniel Kahneman

> "The purely economic man is indeed close to being a social moron. Economic theory has been much preoccupied with this rational fool."
>
> -- Amartya Sen

### Overview {#overview}

------------------------------------------------------------------------

In recent decades, economics has increasingly relied on quantitative models to understand and explore economic phenomena. Central to many of these models is the idea that agents act as rational beings and make rational choices. The emergence of behavioural economics is contextualized as a question of validity to such assumptions and a response to addressing some critical problems that irrationality raises in economic modelling. Integral to this endeavor is understanding the difference between homo-economicus (the economic man) and homo-sapiens (real humans). It is crucial to understand why economic models that assume agents behave as homo-economicus often fail in real life.

The course aims to start from the core assumptions which are often made in economics and then moves on to systematically understand why these are flawed. We then discuss some of the core themes and concepts in behavioural economics. The course aims to explain all these topics using real world examples to show why behavioural economics makes a difference. We then cover the role of behavioural economics in different areas beyond economics.

### Lecture Content {#lecture_content}

------------------------------------------------------------------------

-   Week 1. Homo-economicus OR Homo-sapiens
    -   Day 1. Introductions
    -   Day 2. [Into the World of (ir)Rationality](w1_day2.qmd){style="text-decoration: none"}
    -   Day 3. [Bounds of Rationality](w1_day3.qmd){style="text-decoration: none"}
    -   Day 4. Trip to the Fitzwilliam Museum
    -   Day 5. All About Heuristics

### Reading

------------------------------------------------------------------------

Thaler, R. H., & Sunstein, C. R. (2021). Nudge: The Final Edition. Penguin Publishing.

Thaler, R. H. (2015). *Misbehaving: The making of behavioral economics.* W W Norton & Co.

Kahneman, D. (2011). *Thinking, fast and slow.* Farrar, Straus and Giroux.

### Assessment

------------------------------------------------------------------------

Students will be split into groups of 2 and will be required to research into any industry/theme of their choosing seeing how behavioural economics is used in that industry and come up with ideas about how they can concepts from behavioural economics in that industry. The students will be evaluated based on their presentations of their research in class and a short writeup that would be submitted to the instructor about their research.  
